name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'  # Example: v0.1.0

jobs:
  build-and-publish:
    name: Build and publish Python package
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for trusted publishing
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Set up uv in PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build the package
        run: uv build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # For trusted publishing via PyPI API tokens/OIDC
          # Set `repository-url` if publishing to TestPyPI
          # repository-url: https://test.pypi.org/legacy/
          verbose: true
